### ISSUE TITLE
Crashes on Heroku

### ISSUE THREAD

**Issue by darron** [rauchg/slackin#11]
Here's the error:

```
2015-02-02T20:27:28.201168+00:00 heroku[web.1]: Starting process with command `bin/slackin --port 45132 domain token-goes-here`
2015-02-02T20:27:32.109096+00:00 app[web.1]:
2015-02-02T20:27:32.111335+00:00 app[web.1]: import express from 'express';
2015-02-02T20:27:32.122321+00:00 app[web.1]:     at Module._compile (module.js:439:25)
2015-02-02T20:27:32.122317+00:00 app[web.1]: SyntaxError: Unexpected reserved word
2015-02-02T20:27:32.122323+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2015-02-02T20:27:32.122325+00:00 app[web.1]:     at Object.loader (/app/node_modules/6to5/lib/6to5/register.js:48:16)
2015-02-02T20:27:32.122329+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2015-02-02T20:27:32.122326+00:00 app[web.1]:     at Module.load (module.js:356:32)
2015-02-02T20:27:32.122330+00:00 app[web.1]:     at Module.require (module.js:364:17)
2015-02-02T20:27:32.122332+00:00 app[web.1]:     at require (module.js:380:17)
2015-02-02T20:27:32.122333+00:00 app[web.1]:     at Object.<anonymous> (/app/bin/slackin:19:15)
2015-02-02T20:27:32.122335+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2015-02-02T20:27:32.122336+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2015-02-02T20:27:32.111057+00:00 app[web.1]: /app/lib/index.js:6
2015-02-02T20:27:32.114056+00:00 app[web.1]: ^^^^^^
2015-02-02T20:27:32.947903+00:00 heroku[web.1]: Process exited with status 1
2015-02-02T20:27:33.558357+00:00 heroku[web.1]: State changed from starting to crashed
```

I've been trying this on Heroku and inside of Docker since it was released - this looks like the closest I've gotten so far.

**Comment by joelburget** [comment]
Problem is it's including ecmascript 6 files which apparently Heroku can't handle. I assume that's what the 6to5 business is for, but maybe we need to run node [with some flags](https://github.com/heroku-examples/node-harmony-example)?

**Comment by makenai** [comment]
You'll need to go in and change bin/slackin:

```
-require('6to5/register')({
-  // prevent issues with global installs
-  // and 6to5 ignoring any occurrence of
-  // 'node_modules' by default, including
-  // /usr/local/lib/node_modules, which
-  // makes it noop entirely
-  ignore: false,
-  only: /slackin\/lib\//
-});
+require('6to5/register');
```

Looks like this was recently changed but not tested on heroku.

**Comment by darron** [comment]
Yes - that perfectly fixes the problem. Thanks!

**Comment by llimllib** [comment]
Thank you, I was seeing this as well and it doesn't error once that patch is applied

**Comment by joshuatbrown** [comment]
The `require` fix works for me, too - thanks so much!
