### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by tdrewk** [rauchg/slackin#120]
Anyone have any insight on why we would be receiving this application error?

https://suggestitcommunity.herokuapp.com/

Heroku support responded with the following...

Hi Tom,

I'd recommend taking a look at heroku logs in the CLI, it seems to be connecting to an invalid host:

2015-11-13T01:31:26.462183+00:00 heroku[web.1]: Starting process with command `bin/slackin --channels "$SLACK_CHANNELS" --port 35494 suggestitcommunity.slack.com xoxp-10537258593-10532710582-14401515057-1791530129`
2015-11-13T01:31:29.389530+00:00 app[web.1]: Fri Nov 13 2015 01:31:29 GMT+0000 (UTC) – fetching
2015-11-13T01:31:29.440592+00:00 app[web.1]: Fri Nov 13 2015 01:31:29 GMT+0000 (UTC) – Error: Hostname/IP doesn't match certificate's altnames: "Host: suggestitcommunity.slack.com.slack.com. is not in the cert's altnames: DNS:*.slack.com, DNS:slack.com"
2015-11-13T01:31:29.440595+00:00 app[web.1]:     at Object.checkServerIdentity (tls.js:201:15)
2015-11-13T01:31:29.440596+00:00 app[web.1]:     at TLSSocket.<anonymous> (_tls_wrap.js:1050:29)
2015-11-13T01:31:29.440597+00:00 app[web.1]:     at emitNone (events.js:67:13)
2015-11-13T01:31:29.440598+00:00 app[web.1]:     at TLSSocket.emit (events.js:166:7)
2015-11-13T01:31:29.440598+00:00 app[web.1]:     at TLSSocket._finishInit (_tls_wrap.js:581:8)
2015-11-13T01:31:29.441730+00:00 app[web.1]: Fri Nov 13 2015 01:31:29 GMT+0000 (UTC) – retrying
2015-11-13T01:31:29.415731+00:00 app[web.1]: Fri Nov 13 2015 01:31:29 GMT+0000 (UTC) – listening on 0.0.0.0:35494
2015-11-13T01:31:29.446303+00:00 app[web.1]: /app/node/slack.js:48
2015-11-13T01:31:29.446306+00:00 app[web.1]:           var team = res.body.team;
2015-11-13T01:31:29.446307+00:00 app[web.1]:                         ^
2015-11-13T01:31:29.446310+00:00 app[web.1]:     at /app/node/slack.js:48:25
2015-11-13T01:31:29.446308+00:00 app[web.1]: 
2015-11-13T01:31:29.446311+00:00 app[web.1]:     at Request.callback (/app/node_modules/superagent/lib/node/index.js:746:30)
2015-11-13T01:31:29.446312+00:00 app[web.1]:     at ClientRequest.<anonymous> (/app/node_modules/superagent/lib/node/index.js:711:10)
2015-11-13T01:31:29.446309+00:00 app[web.1]: TypeError: Cannot read property 'body' of undefined
2015-11-13T01:31:29.446314+00:00 app[web.1]:     at TLSSocket.socketErrorListener (_http_client.js:265:9)
2015-11-13T01:31:29.446312+00:00 app[web.1]:     at emitOne (events.js:77:13)
2015-11-13T01:31:29.446313+00:00 app[web.1]:     at ClientRequest.emit (events.js:169:7)
2015-11-13T01:31:29.446314+00:00 app[web.1]:     at emitOne (events.js:77:13)
2015-11-13T01:31:29.446315+00:00 app[web.1]:     at TLSSocket.emit (events.js:169:7)
2015-11-13T01:31:29.446316+00:00 app[web.1]:     at emitErrorNT (net.js:1253:8)
2015-11-13T01:31:29.446317+00:00 app[web.1]:     at doNTCallback2 (node.js:450:9)
2015-11-13T01:31:30.202674+00:00 heroku[web.1]: Process exited with status 1
2015-11-13T01:31:30.215586+00:00 heroku[web.1]: State changed from starting to crashed
Hope that helps,
Steven

**Comment by ezy** [comment]
Good feedback. For anyone else who visits this, the error is caused by entering the wrong SLACK_SUBDOMAIN details. The SLACK_SUBDOMAIN should only be the channel name without the "slack.com" url attached. So in this case it would be "suggestitcommunity" NOT "suggestitcommunity.slack.com".

**Comment by tdrewk** [comment]
Doah, such a goober move on my part. Thanks Ezy

**Comment by ezy** [comment]
Hey my pleasure - I had the same issue (we're all secretly goobers), but only clicked from the log you posted:

`Hostname/IP doesn't match certificate's altnames: "Host: suggestitcommunity.slack.com.slack.com. `

 :smile:

**Comment by rauchg** [comment]
Seems like this is something we run into a lot. If anyone here wants to contribute code to clean up `/\.slack\.com$` from the supplied subdomain, it'd be amazing!!
