### ISSUE TITLE
Deployment to OpenShift broken after latest update?

### ISSUE THREAD

**Issue by Stoner19** [rauchg/slackin#136]
Its possible that I'm missing something, but from what I can tell something has changed in the latest version that causes deployment to OpenShift to break.

`remote: npm WARN package.json slackin@0.8.1 No repository field.
remote: npm WARN package.json slackin@0.8.1 No license field.
remote: npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0 `

and 

`remote: make: *** [Release/obj.target/validation/src/validation.o] Error 1
remote: gyp ERR! build error 
remote: gyp ERR! stack Error: `make` failed with exit code: 2
remote: gyp ERR! stack     at ChildProcess.onExit (/var/lib/openshift/569583602d5271d51f000088/app-root/data/.iojs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
remote: gyp ERR! stack     at emitTwo (events.js:87:13)
remote: gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
remote: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
remote: gyp ERR! System Linux 2.6.32-573.12.1.el6.x86_64
remote: gyp ERR! command "/var/lib/openshift/569583602d5271d51f000088/app-root/data/.iojs/bin/iojs" "/var/lib/openshift/569583602d5271d51f000088/app-root/data/.iojs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote: gyp ERR! cwd /var/lib/openshift/569583602d5271d51f000088/app-root/runtime/repo/node_modules/utf-8-validate
remote: gyp ERR! node -v v3.3.1
remote: gyp ERR! node-gyp -v v3.2.1
remote: gyp ERR! not ok 
remote: npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
remote: npm WARN install:utf-8-validate@1.2.1 Exit status 1
remote: 
remote: > slackin@0.8.1 postinstall /var/lib/openshift/569583602d5271d51f000088/app-root/runtime/repo
remote: > gulp
remote: 
remote: [18:05:21] Requiring external module babel-core/register
remote: [18:05:22] Using gulpfile /var/lib/openshift/569583602d5271d51f000088/app-root/runtime/repo/gulpfile.babel.js
remote: fs.js:549
remote:   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
remote:                                                   ^
remote: 
remote: Error: EACCES: permission denied, open '/var/lib/openshift/569583602d5271d51f000088/.babel.json'
remote:     at Error (native)
remote:     at Object.fs.openSync (fs.js:549:18)
remote:     at Object.fs.writeFileSync (fs.js:1155:15)
remote:     at save (/var/lib/openshift/569583602d5271d51f000088/app-root/runtime/repo/node_modules/babel-register/lib/cache.js:45:19)
remote:     at doNTCallback0 (node.js:407:9)
remote:     at process._tickCallback (node.js:336:13)
remote: 
remote: npm WARN slackin@0.8.1 No repository field.
remote: npm WARN slackin@0.8.1 No license field.
remote: npm ERR! Linux 2.6.32-573.12.1.el6.x86_64
remote: npm ERR! argv "/var/lib/openshift/569583602d5271d51f000088/app-root/data/.iojs/bin/iojs" "/var/lib/openshift/569583602d5271d51f000088/app-root/data/.iojs/bin/npm" "i"
remote: npm ERR! node v3.3.1
remote: npm ERR! npm  v3.5.3
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! slackin@0.8.1 postinstall: `gulp`
remote: npm ERR! Exit status 1
remote: npm ERR! 
remote: npm ERR! Failed at the slackin@0.8.1 postinstall script 'gulp'.
remote: npm ERR! Make sure you have the latest version of node.js and npm installed.
remote: npm ERR! If you do, this is most likely a problem with the slackin package,
remote: npm ERR! not with npm itself.
remote: npm ERR! Tell the author that this fails on your system:
remote: npm ERR!     gulp
remote: npm ERR! You can get information on how to open an issue for this project with:
remote: npm ERR!     npm bugs slackin
remote: npm ERR! Or if that isn't available, you can get their info via:
remote: npm ERR!     npm owner ls slackin
remote: npm ERR! There is likely additional logging output above.
remote: 
remote: npm ERR! Please include the following file with any support request:
remote: npm ERR!     /var/lib/openshift/569583602d5271d51f000088/app-root/runtime/repo/npm-debug.log
remote: CLIENT_RESULT: io.js modules installed.
remote: Preparing build for deployment
remote: Deployment id is fe4008e2
remote: Activating deployment
remote: CLIENT_MESSAGE: Starting io.js application...
remote: CLIENT_RESULT: Warning! Could not start io.js application!
remote: -------------------------
remote: Git Post-Receive Result: failure
remote: Activation status: failure
remote: Activation failed for the following gears:
remote: 569583602d5271d51f000088 (Error activating gear: CLIENT_ERROR: Failed to execute: 'control start' for /var/lib/openshift/569583602d5271d51f000088/iojs
remote: #<IO:0x000000025ee2d0>
remote: #<IO:0x000000025ee258>
remote: )
remote: Deployment completed with status: failure
remote: postreceive failed
To ssh://569583602d5271d51f000088@slackin-test.rhcloud.com/~/git/slackin.git/
 + 0bcc963...fcaae54 master -> master (forced update)`

There is nothing in the ` /var/lib/openshift/569583602d5271d51f000088/app-root/runtime/repo/npm-debug.log` file, nor is there even a `/var/lib/openshift` directory

**Comment by nsvrana** [comment]
I just wanted to note I had the same problem when deploying in the node:4.2 docker image. I had to roll back to slackin@0.7.3 to get it to work.

**Comment by Stoner19** [comment]
@nsvrana reverting back to 0.7.3 fixed it for me as well.

**Comment by joshelson** [comment]
This can be fixed with the following command:

rhc env-set -a slackin BABEL_CACHE_PATH="/var/lib/openshift/{instance}/app-root/repo/.cache/.babel.json"

Might be a more elegant way to do it to grab the path in an automated way, but that should fix that error.

**Comment by GraemeFulton** [comment]
reverting to 0.7.3 also fixed it for me, the fix from @joshelson didn't seem to work for me

**Comment by Lopera** [comment]
@joshelson command did not work for me, even after restart Slackin application on OpenShift. Any idea why ?? 
Or can someone explain me how to rever to 0.7.3 ? 

```
Welcome to io.js on OpenShift!

Everything seems to be in order.

Running io.js:
- http_parser: 2.5.0
- node: 3.3.1
- v8: 4.4.63.30
- uv: 1.7.4
- zlib: 1.2.8
- ares: 1.10.1-DEV
- modules: 45
- openssl: 1.0.2d
```

![captura de pantalla 2016-04-28 a las 10 02 04 a m](https://cloud.githubusercontent.com/assets/7819566/14890492/81e7eb1a-0d28-11e6-9368-d419b00aa44d.png)

Thanks !!

**Comment by GraemeFulton** [comment]
@Lopera - you can change the version number inside package.json, line 3 as shown below: 
<img width="340" alt="captura de pantalla 2016-04-28 a las 16 11 58" src="https://cloud.githubusercontent.com/assets/4354786/14890846/0344af58-0d5c-11e6-8f99-fd7937da315f.png">

**Comment by Lopera** [comment]
... I am lost :-/ Where is located that file ?

I found a `package.json` in rhc application at `slackin-jlopera.rhcloud.com 57221dab0c1e66243f0001a1` folder `/git/slackin.git/` but is a different file.

![captura de pantalla 2016-04-28 a las 11 33 41 a m](https://cloud.githubusercontent.com/assets/7819566/14893681/f4ad92fa-0d35-11e6-92e7-941ea0aa4f3e.png)

The one you show me is in the `slackin-master`, I change that value, but I don't know how to update the rhc application with that one.

![captura de pantalla 2016-04-28 a las 11 03 48 a m](https://cloud.githubusercontent.com/assets/7819566/14893694/03cc2bf2-0d36-11e6-927d-9b2dca6a23fa.png)

**Comment by GraemeFulton** [comment]
@Lopera I'd suggest just starting again from step 5 of the [instructions](https://github.com/rauchg/slackin/wiki/OpenShift) 

As soon as you clone the repo, there should be a package.json in the root of the directory you have just created, the folder structure should be just like the repo: https://github.com/rauchg/slackin. The package.json I refer to is the one right there: https://github.com/rauchg/slackin/blob/master/package.json
Change that to the version you want, and then continue step 5. 

See how that goes 👍

**Comment by joshelson** [comment]
Just because I may not have been specific enough before, the set-env command I reference above needs to be run on a "clean" OpenShift instance before you've attempted to clone and deploy the code.  If you do it after the fact, it won't work quite how you expect.

**Comment by Lopera** [comment]
Thanks @GraemeFulton @joshelson I'll keep trying. I'll tell you when it works :-)
