### ISSUE TITLE
Clean install on heroku fails to run

### ISSUE THREAD

**Issue by davehodg** [rauchg/slackin#138]
When starting the app, we get this in the logs:

2016-01-16T13:50:57.223915+00:00 app[web.1]: Sat Jan 16 2016 13:50:57 GMT+0000 (UTC) – fetching
2016-01-16T13:50:57.246395+00:00 app[web.1]: Sat Jan 16 2016 13:50:57 GMT+0000 (UTC) – listening on 0.0.0.0:55948
2016-01-16T13:50:57.487587+00:00 app[web.1]: /app/node/slack.js:53
2016-01-16T13:50:57.487589+00:00 app[web.1]:         (res.body.channels || []).forEach(function (channel) {
2016-01-16T13:50:57.487590+00:00 app[web.1]:             ^
2016-01-16T13:50:57.487590+00:00 app[web.1]: 2016-01-16T13:50:57.487590+00:00 app[web.1]: 
2016-01-16T13:50:57.487595+00:00 app[web.1]:     at ClientRequest.emit (events.js:169:7)
2016-01-16T13:50:57.487596+00:00 app[web.1]:     at TLSSocket.socketErrorListener (_http_client.js:264:9)
2016-01-16T13:50:58.089763+00:00 heroku[web.1]: Process exited with status 1
2016-01-16T13:50:58.105546+00:00 heroku[web.1]: State changed from starting to crashed
2016-01-16T13:50:57.487594+00:00 app[web.1]:     at Request.callback (/app/node_modules/superagent/lib/node/index.js:746:30)
2016-01-16T13:50:57.487594+00:00 app[web.1]:     at ClientRequest.<anonymous> (/app/node_modules/superagent/lib/node/index.js:711:10)
2016-01-16T13:50:57.487595+00:00 app[web.1]:     at emitOne (events.js:77:13)
2016-01-16T13:50:57.487596+00:00 app[web.1]:     at TLSSocket.socketErrorListener (_http_client.js:264:9)
2016-01-16T13:50:57.487596+00:00 app[web.1]:     at emitOne (events.js:77:13)
2016-01-16T13:50:57.487597+00:00 app[web.1]:     at TLSSocket.emit (events.js:169:7)
2016-01-16T13:50:58.089763+00:00 heroku[web.1]: Process exited with status 1

Any ideas?

**Comment by davehodg** [comment]
I did a clean test install and it was fine. I assume my colleague got something wrong in the install.

**Comment by reinikainen** [comment]
The above error is generated when the problem is sitting in the chair, nothing to do with the code.  It happens when the full slack team domain (including the slack.com) is entered rather than just the subdomain as the instructions indicate.

**Comment by davehodg** [comment]
Then I'll close the issue. There should possibly be a check in the code?
