### ISSUE TITLE
Heroku Install Error

### ISSUE THREAD

**Issue by Sazuko3** [rauchg/slackin#141]
I got a problem and i have no idea what to do. I hope one of you could help.

I created an app on heroku with this and i got the following error:

2016-01-22T03:01:28.371276+00:00 heroku[web.1]: State changed from crashed to starting
2016-01-22T03:01:31.532647+00:00 heroku[web.1]: Starting process with command `bin/slackin --coc "$SLACK_COC" --channels "$SLACK_CHANNELS" --port 59595 communitychat.slack.com xoxp-18092061297-18099655143-19138003569-c4c313c5b4`
2016-01-22T03:01:33.962299+00:00 app[web.1]: Fri Jan 22 2016 03:01:33 GMT+0000 (UTC) – listening on 0.0.0.0:59595
2016-01-22T03:01:34.212397+00:00 app[web.1]: Fri Jan 22 2016 03:01:34 GMT+0000 (UTC) – Error: Hostname/IP doesn't match certificate's altnames: "Host: communitychat.slack.com.slack.com. is not in the cert's altnames: DNS:*.slack.com, DNS:slack.com"
2016-01-22T03:01:34.212401+00:00 app[web.1]:     at Object.checkServerIdentity (tls.js:201:15)
2016-01-22T03:01:34.212402+00:00 app[web.1]:     at TLSSocket.<anonymous> (_tls_wrap.js:1063:29)
2016-01-22T03:01:34.212403+00:00 app[web.1]:     at emitNone (events.js:67:13)
2016-01-22T03:01:34.212404+00:00 app[web.1]:     at TLSSocket.emit (events.js:166:7)
2016-01-22T03:01:34.212405+00:00 app[web.1]:     at TLSSocket._finishInit (_tls_wrap.js:596:8)
2016-01-22T03:01:33.933056+00:00 app[web.1]: Fri Jan 22 2016 03:01:33 GMT+0000 (UTC) – fetching
2016-01-22T03:01:34.219407+00:00 app[web.1]: /app/node/slack.js:59
2016-01-22T03:01:34.219410+00:00 app[web.1]:         var team = res.body.team;
2016-01-22T03:01:34.219411+00:00 app[web.1]:                       ^
2016-01-22T03:01:34.219412+00:00 app[web.1]: 
2016-01-22T03:01:34.219413+00:00 app[web.1]:     at /app/node/slack.js:59:23
2016-01-22T03:01:34.219413+00:00 app[web.1]: TypeError: Cannot read property 'body' of undefined
2016-01-22T03:01:34.219414+00:00 app[web.1]:     at Request.callback (/app/node_modules/superagent/lib/node/index.js:746:30)
2016-01-22T03:01:34.219415+00:00 app[web.1]:     at ClientRequest.<anonymous> (/app/node_modules/superagent/lib/node/index.js:711:10)
2016-01-22T03:01:34.219418+00:00 app[web.1]:     at emitOne (events.js:77:13)
2016-01-22T03:01:34.219417+00:00 app[web.1]:     at ClientRequest.emit (events.js:169:7)
2016-01-22T03:01:34.219416+00:00 app[web.1]:     at emitOne (events.js:77:13)
2016-01-22T03:01:34.219418+00:00 app[web.1]:     at TLSSocket.socketErrorListener (_http_client.js:264:9)
2016-01-22T03:01:34.219421+00:00 app[web.1]:     at nextTickCallbackWith2Args (node.js:478:9)
2016-01-22T03:01:34.219419+00:00 app[web.1]:     at TLSSocket.emit (events.js:169:7)
2016-01-22T03:01:34.219420+00:00 app[web.1]:     at emitErrorNT (net.js:1256:8)
2016-01-22T03:01:34.214751+00:00 app[web.1]: Fri Jan 22 2016 03:01:34 GMT+0000 (UTC) – retrying
2016-01-22T03:01:35.018796+00:00 heroku[web.1]: Process exited with status 1
2016-01-22T03:01:35.032380+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by rauchg** [comment]
> "Host: communitychat.slack.com.slack.com. is not in the cert's altnames: DNS:*.slack.com, DNS:slack.com"

Seems like you included `communitychat.slack.com` instead of just `communitychat` in the config. Maybe we should sanitize this so that people don't run into this issue (filter out `.slack.com` if present). PR welcome
