### ISSUE TITLE
Openshift Error: EACCES: permission denied, mkdir '/var/lib/openshift/{instance}'

### ISSUE THREAD

**Issue by BitterLox** [rauchg/slackin#155]
(0)-(16:49:40 2016-02-27)(Sab)-> (~/opt/slackin)-(15 files, 840K)-> git push openshift master --force
Counting objects: 838, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (316/316), done.
Writing objects: 100% (838/838), 254.67 KiB | 0 bytes/s, done.
Total 838 (delta 494), reused 838 (delta 494)
remote: CLIENT_MESSAGE: Stopping io.js application...
remote: CLIENT_RESULT: io.js application stopped.
remote: Building git ref 'master', commit e3d3194
remote: npm WARN package.json slackin@0.8.2 No repository field.
remote: npm WARN package.json slackin@0.8.2 No license field.
remote: npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
remote: npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
remote: npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
remote: 
remote: > slackin@0.8.2 postinstall /var/lib/openshift/56d1c4d97628e1a3ce000138/app-root/runtime/repo
remote: > gulp
remote: 
remote: [10:50:52] Requiring external module babel-core/register
remote: [10:50:52] Using gulpfile /var/lib/openshift/56d1c4d97628e1a3ce000138/app-root/runtime/repo/gulpfile.babel.js
remote: /var/lib/openshift/56d1c4d97628e1a3ce000138/app-root/runtime/repo/node_modules/mkdirp/index.js:90
remote:                     throw err0;
remote:                     ^
remote: 
remote: Error: EACCES: permission denied, mkdir '/var/lib/openshift/{instance}'
remote:     at Error (native)
remote:     at Object.fs.mkdirSync (fs.js:799:18)
remote:     at sync (/var/lib/openshift/56d1c4d97628e1a3ce000138/app-root/runtime/repo/node_modules/mkdirp/index.js:71:13)
remote:     at sync (/var/lib/openshift/56d1c4d97628e1a3ce000138/app-root/runtime/repo/node_modules/mkdirp/index.js:77:24)
remote:     at sync (/var/lib/openshift/56d1c4d97628e1a3ce000138/app-root/runtime/repo/node_modules/mkdirp/index.js:77:24)
remote:     at Function.sync (/var/lib/openshift/56d1c4d97628e1a3ce000138/app-root/runtime/repo/node_modules/mkdirp/index.js:77:24)
remote:     at save (/var/lib/openshift/56d1c4d97628e1a3ce000138/app-root/runtime/repo/node_modules/babel-register/lib/cache.js:47:11)
remote:     at doNTCallback0 (node.js:407:9)
remote:     at process._tickCallback (node.js:336:13)
remote: 
remote: 
remote: CLIENT_RESULT: io.js modules installed.
remote: Preparing build for deployment
remote: Deployment id is 3a711a90
remote: Activating deployment
remote: CLIENT_MESSAGE: Starting io.js application...
remote: CLIENT_RESULT: Warning! Could not start io.js application!
remote: -------------------------
remote: Git Post-Receive Result: failure
remote: Activation status: failure
remote: Activation failed for the following gears:
remote: 56d1c4d97628e1a3ce000138 (Error activating gear: CLIENT_ERROR: Failed to execute: 'control start' for /var/lib/openshift/56d1c4d97628e1a3ce000138/iojs
remote: #<IO:0x00000000ed62a0>
remote: #<IO:0x00000000ed6228>
remote: )
remote: Deployment completed with status: failure
remote: postreceive failed
To ssh://56d1c4d97628e1a3ce000138@slackin-conslackin.rhcloud.com/~/git/slackin.git/
 + 40ab04e...e3d3194 master -> master (forced update)

Openshift deployment is broken? Seems like a permission issue but i can't figure out how to fix it, open shift doesn't give root permissions.

**Comment by zrenet** [comment]
I have same problem on Open Shift (in Heroku is OK)

I add a variable BABEL_DISABLE_CACHE=1
The web can access but can not invite, stuck in please wait button.
Please help us.

**Comment by jeroenleenarts** [comment]
Does the suggestion in #136 fix it?

**Comment by vyahhi** [comment]
@jeroenleenarts I had the same problem, and https://github.com/rauchg/slackin/issues/136#issuecomment-183449142 fixed it for me.
