### ISSUE TITLE
Issues with set up in heroku

### ISSUE THREAD

**Issue by talenyc** [rauchg/slackin#160]
After the heroku installation I try to browse to my app but I get an error. From logs I see:
2016-03-03T04:20:42.090030+00:00 app[web.1]:     at Request.callback (/app/node_modules/superagent/lib/node/index.js:746:30)
2016-03-03T04:20:42.090044+00:00 app[web.1]:     at ClientRequest.emit (events.js:182:7)
2016-03-03T04:20:42.090046+00:00 app[web.1]:     at emitOne (events.js:90:13)
2016-03-03T04:20:42.090046+00:00 app[web.1]:     at TLSSocket.emit (events.js:182:7)
2016-03-03T04:20:43.039491+00:00 heroku[web.1]: Process exited with status 1
2016-03-03T04:20:43.085855+00:00 heroku[web.1]: State changed from starting to crashed
2016-03-03T04:20:45.295156+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico"

**Comment by makkaba** [comment]
me too. 
i think heroku installation has some problem.
even though i tried it several times, the application doesn't work.

**Comment by metatrevor** [comment]
Experiencing the same issue as well.

**Comment by alexpls** [comment]
I had this issue but then used altered the Heroku deploy link so that it deploys straight from the master branch instead of the 0.8.3 tag. This is the link I used which worked: https://heroku.com/deploy?template=https://github.com/rauchg/slackin/tree/master

**Comment by mrmayfield** [comment]
I'm getting:

```
2016-04-03T19:44:30.571689+00:00 app[web.1]: /app/node/slack.js:53
2016-04-03T19:44:30.571704+00:00 app[web.1]:         (res.body.channels || []).forEach(function (channel) {
2016-04-03T19:44:30.571706+00:00 app[web.1]:             ^
2016-04-03T19:44:30.571707+00:00 app[web.1]:
2016-04-03T19:44:30.571707+00:00 app[web.1]: TypeError: Cannot read property 'body' of undefined
2016-04-03T19:44:30.571708+00:00 app[web.1]:     at /app/node/slack.js:53:13
2016-04-03T19:44:30.571720+00:00 app[web.1]:     at Request.callback (/app/node_modules/superagent/lib/node/index.js:746:30)
2016-04-03T19:44:30.571722+00:00 app[web.1]:     at ClientRequest.<anonymous> (/app/node_modules/superagent/lib/node/index.js:711:10)
2016-04-03T19:44:30.571722+00:00 app[web.1]:     at emitOne (events.js:90:13)
2016-04-03T19:44:30.571723+00:00 app[web.1]:     at ClientRequest.emit (events.js:182:7)
2016-04-03T19:44:30.571724+00:00 app[web.1]:     at TLSSocket.socketErrorListener (_http_client.js:295:9)
2016-04-03T19:44:30.571724+00:00 app[web.1]:     at emitOne (events.js:90:13)
2016-04-03T19:44:30.571725+00:00 app[web.1]:     at TLSSocket.emit (events.js:182:7)
2016-04-03T19:44:30.571725+00:00 app[web.1]:     at connectErrorNT (net.js:996:8)
2016-04-03T19:44:30.571726+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

Maybe my token is wrong? Not sure

**Comment by mrmayfield** [comment]
Okay, got it fixed, `SLACK_SUBDOMAIN` threw me off, I guess it should just be SLACK_TEAMNAME or something like that, because `https://tinderjs.slack.com` failed but `tinderjs` worked.

**Comment by brianroach** [comment]
@mrmayfield you're a genius! got it working with that one tip alone. Bam!

**Comment by nitinsurana** [comment]
Unable to deploy using `master` branch on `heroku`. Getting the following error

```
2016-06-18T07:45:37.731955+00:00 app[web.1]: Error: Cannot find module './../node'
2016-06-18T07:45:37.731956+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:339:15)
2016-06-18T07:45:37.731957+00:00 app[web.1]:     at Function.Module._load (module.js:290:25)
2016-06-18T07:45:37.731957+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-06-18T07:45:37.731958+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-06-18T07:45:37.731958+00:00 app[web.1]:     at Object.<anonymous> (/app/bin/slackin:5:15)
2016-06-18T07:45:37.731959+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-06-18T07:45:37.731960+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-06-18T07:45:37.731960+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-06-18T07:45:37.731961+00:00 app[web.1]:     at Function.Module.runMain (module.js:447:10)
```

**Comment by alexpls** [comment]
@nitinsurana you're right... this isn't a heroku only issue but seems to happen on any attempt to run `slackin` from `master` branch. I've created a PR to hopefully resolve this: #204

**Comment by leo** [comment]
Fixed in https://github.com/rauchg/slackin/pull/208
