### ISSUE TITLE
500 after Deploy to Azure

### ISSUE THREAD

**Issue by hoetz** [rauchg/slackin#187]
After deploying to Azure I get a 500 from the site.
KUDU logs show this application error below. I tried to follow the instructions as close as possible.

Mon Apr 18 2016 08:12:11 GMT+0000 (Coordinated Universal Time): Unaught exception: TypeError: Cannot read property 'name' of undefined
    at D:\home\site\wwwroot\node\slack.js:60:31
    at Request.callback (D:\home\site\wwwroot\node_modules\superagent\lib\node\index.js:746:30)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\superagent\lib\node\index.js:135:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Stream.<anonymous> (D:\home\site\wwwroot\node_modules\superagent\lib\node\index.js:938:12)
    at emitNone (events.js:72:20)
    at Stream.emit (events.js:166:7)
    at Unzip.<anonymous> (D:\home\site\wwwroot\node_modules\superagent\lib\node\utils.js:124:12)
    at emitNone (events.js:72:20) 

Update: just to be clear, I used this as my api token
![unbenannt](https://cloud.githubusercontent.com/assets/3835948/14598221/70e15100-0551-11e6-91eb-c2c17436de2d.png)

**Comment by hoetz** [comment]
Fixed. you actually have to take a Token for Test & development not the client secret...
