### ISSUE TITLE
Error when trying to deploy to OpenShift

### ISSUE THREAD

**Issue by raju-bitter** [rauchg/slackin#191]
Followed this guide https://github.com/rauchg/slackin/wiki/OpenShift to get slackin up and running on OpenShift. When running locally with node.js, everything is working fine.

```
Spitsbergen:slackin raju$ git remote add openshift `rhc app-show slackin | grep Git | sed 's/^.*ssh/ssh/'`
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Spitsbergen:slackin raju$ git push openshift master --force
Counting objects: 965, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (354/354), done.
Writing objects: 100% (965/965), 285.08 KiB | 0 bytes/s, done.
Total 965 (delta 583), reused 965 (delta 583)
remote: CLIENT_MESSAGE: Stopping io.js application...
remote: CLIENT_RESULT: io.js application stopped.
remote: Building git ref 'master', commit 4792492
remote: npm WARN package.json slackin@0.8.3 No repository field.
remote: npm WARN package.json slackin@0.8.3 No license field.
remote: npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
remote: npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
remote: npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
remote:
remote: > slackin@0.8.3 postinstall /var/lib/openshift/572047b489f5cf8607000013/app-root/runtime/repo
remote: > gulp
remote:
remote: [01:06:20] Requiring external module babel-core/register
remote: [01:06:21] Using gulpfile /var/lib/openshift/572047b489f5cf8607000013/app-root/runtime/repo/gulpfile.babel.js
remote: fs.js:549
remote:   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
remote:                                                   ^
remote:
remote: Error: EACCES: permission denied, open '/var/lib/openshift/572047b489f5cf8607000013/.babel.json'
remote:     at Error (native)
remote:     at Object.fs.openSync (fs.js:549:18)
remote:     at Object.fs.writeFileSync (fs.js:1155:15)
remote:     at save (/var/lib/openshift/572047b489f5cf8607000013/app-root/runtime/repo/node_modules/babel-register/lib/cache.js:48:19)
remote:     at doNTCallback0 (node.js:407:9)
remote:     at process._tickCallback (node.js:336:13)
remote:
remote:
remote: CLIENT_RESULT: io.js modules installed.
remote: Preparing build for deployment
remote: Deployment id is 21df7713
remote: Activating deployment
remote: CLIENT_MESSAGE: Starting io.js application...
remote: CLIENT_RESULT: Warning! Could not start io.js application!
remote: -------------------------
remote: Git Post-Receive Result: failure
remote: Activation status: failure
remote: Activation failed for the following gears:
remote: 572047b489f5cf8607000013 (Error activating gear: CLIENT_ERROR: Failed to execute: 'control start' for /var/lib/openshift/572047b489f5cf8607000013/iojs
remote: #<IO:0x000000006e0280>
remote: #<IO:0x000000006e0208>
remote: )
remote: Deployment completed with status: failure
remote: postreceive failed
To ssh://572047b489f5cf8607000013@slackin-dreemproject.rhcloud.com/~/git/slackin.git/
 + abca14b...4792492 master -> master (forced update)
Spitsbergen:slackin raju$ rhc tail slackin
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/slackin
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs slackin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls slackin
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /var/lib/openshift/572047b489f5cf8607000013/app-root/runtime/repo/npm-debug.log
```

**Comment by benflinn** [comment]
same problem for me

**Comment by joshuatuscan** [comment]
same over here!

**Comment by benflinn** [comment]
try adding in this env variable and try again:

`rhc env-set -a slackin BABEL_CACHE_PATH="~/app-deployments/current/repo/.babel.json"`

that line should also be added to the wiki for deploying on openshift
