### ISSUE TITLE
TypeError: Object [object Object] has no method 'filter'

### ISSUE THREAD

**Issue by martindale** [rauchg/slackin#201]
Seems like the users array isn't always created.

```
/home/eric/slackin/node/slack.js:96
        users = users.filter(function (x) {
                      ^
TypeError: Object [object Object] has no method 'filter'
    at SlackData.onres (/home/eric/slackin/node/slack.js:96:23)
    at /home/eric/slackin/node/slack.js:61:17
    at Request.callback (/home/eric/slackin/node_modules/superagent/lib/node/index.js:746:30)
    at Request.<anonymous> (/home/eric/slackin/node_modules/superagent/lib/node/index.js:135:10)
    at Request.emit (events.js:95:17)
    at Stream.<anonymous> (/home/eric/slackin/node_modules/superagent/lib/node/index.js:938:12)
    at Stream.emit (events.js:117:20)
    at Unzip.<anonymous> (/home/eric/slackin/node_modules/superagent/lib/node/utils.js:124:12)
    at Unzip.emit (events.js:117:20)
    at _stream_readable.js:944:16
```

**Comment by josenicomaia** [comment]
I got the same problem.

![image](https://cloud.githubusercontent.com/assets/1703754/16995866/ec4dbfb4-4e84-11e6-8fb9-78fdf457b4d8.png)

**Comment by jordanh** [comment]
Ditto that:

![image](https://cloud.githubusercontent.com/assets/103000/17622949/7fd251d0-606b-11e6-95bf-d37350777952.png)

**Comment by jordanh** [comment]
Interesting. It looks like the only way this could happen is if something subtly goes wrong with the slack API call:

https://github.com/rauchg/slackin/blob/1f14de089b1d3db6d232d051bc3122e736ab98b5/lib/slack.js#L44

**Comment by jordanh** [comment]
Created a branch here to experiment: https://github.com/ParabolInc/slackin/tree/fetch-users-defense-%23201

**Comment by jordanh** [comment]
After 2 weeks, our Slackin instance hasn't crashed. According to our devops logs, that's a new record. I think we squashed this one. I'll submit a PR.
