### ISSUE TITLE
Slackin 

### ISSUE THREAD

**Issue by LS-Kai** [rauchg/slackin#205]
I'm trying to install Slackin using the "Deploy to Heroku" button in the readme. When I try to run the application I'm presented with an "Application Error" screen.

I've looked at other issue reports but I haven't found a solution yet.

Here's my log:
`app[web.1]:     at Function.Module._load (module.js:290:25)
app[web.1]:     at Module.require (module.js:367:17)
app[web.1]:     at Module.load (module.js:357:32)
app[web.1]:     at Object.<anonymous> (/app/bin/slackin:5:15)
app[web.1]:     at require (internal/module.js:20:19)
app[web.1]:     at Function.Module.runMain (module.js:447:10)
app[web.1]:     at Function.Module._load (module.js:314:12)
heroku[web.1]: State changed from starting to crashed
heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=letstalkvr.herokuapp.com request_id=abca4487-c486-4bd2-99ad-64db69dbc934 fwd="216.211.94.31" dyno= connect= service= status=503 bytes=
heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=letstalkvr.herokuapp.com request_id=f9ad2d38-f77e-41ea-b885-3a4ea903f7b1 fwd="216.211.94.31" dyno= connect`

**Comment by LS-Kai** [comment]
A (fairly old) blog post I found on the subject says:
> The original slackin repo only supports paid account, we made submitted a PR but it hasn’t been merged yet.
After switching to the [poster's fork](https://github.com/Wiredcraft/slackin) there are no issues.

**Comment by alexpls** [comment]
I believe this is a duplicate of #203

**Comment by leo** [comment]
Fixed in https://github.com/rauchg/slackin/pull/208

**Comment by vinodkone** [comment]
I get the same/similar error

```
2016-06-24T18:31:30.499028+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-06-24T18:31:30.499029+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-06-24T18:31:30.499026+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-06-24T18:31:31.565928+00:00 heroku[web.1]: Process exited with status 1
2016-06-24T21:43:34.190478+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=mesos-slackin.herokuapp.com request_id=563b6d5c-2078-42d3-8886-baea2190d653 fwd="199.116.75.18" dyno= connect= service= status=503 bytes=
2016-06-24T21:43:35.844678+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=mesos-slackin.herokuapp.com request_id=50c9af92-b6f1-4717-bde5-90e83e4d2dc2 fwd="199.116.75.18" dyno= connect= service= status=503 bytes=
2016-06-24T21:43:36.379255+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=mesos-slackin.herokuapp.com request_id=df668808-4ff5-4bb0-92c7-db2d8f437e81 fwd="199.116.75.18" dyno= connect= service= status=503 bytes=
```

**Comment by Tiberriver256** [comment]
Same issue as @vinodkone:

```
2016-08-06T18:26:00.949345+00:00 heroku[web.1]: Process exited with status 1
2016-08-06T18:26:00.893520+00:00 app[web.1]: module.js:341
2016-08-06T18:26:00.893533+00:00 app[web.1]:     throw err;
2016-08-06T18:26:00.893537+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-08-06T18:26:00.962621+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by gtyler** [comment]
Same issue here as well. Testing on a paid Heroku account as well. 

`2016-08-17T20:22:09.056964+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:339:15)
2016-08-17T20:22:09.056944+00:00 app[web.1]: module.js:341
2016-08-17T20:22:09.056962+00:00 app[web.1]: 
2016-08-17T20:22:09.056966+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-08-17T20:22:09.056961+00:00 app[web.1]:     throw err;
2016-08-17T20:22:09.056966+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-08-17T20:22:09.056961+00:00 app[web.1]:     ^
2016-08-17T20:22:09.056963+00:00 app[web.1]: Error: Cannot find module './../dist'
2016-08-17T20:22:09.056965+00:00 app[web.1]:     at Function.Module._load (module.js:290:25)
2016-08-17T20:22:09.056969+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-08-17T20:22:09.056969+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-08-17T20:22:09.056968+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-08-17T20:22:09.056968+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-08-17T20:22:09.056967+00:00 app[web.1]:     at Object.<anonymous> (/app/bin/slackin:5:15)
2016-08-17T20:22:09.056970+00:00 app[web.1]:     at Function.Module.runMain (module.js:447:10)
2016-08-17T20:22:09.102856+00:00 heroku[web.1]: Process exited with status 1
`

**Comment by gtyler** [comment]
FYI: Switched to other fork and this works:

https://github.com/Wiredcraft/slackin
