### ISSUE TITLE
[heroku] Application Error

### ISSUE THREAD

**Issue by byaka** [rauchg/slackin#233]
Deplyed to heroku via default script.
When i try to open https://slackin--byaka.herokuapp.com/ i have only error page.

in log
```
2016-09-06T16:39:14.486333+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=slackin--byaka.herokuapp.com request_id=c3fa50b4-25fc-49c6-a9ed-40f8d643ed77 fwd="<IP>" dyno= connect= service= status=503 bytes=
```

status 503 mean that service not availible, but why?

**Comment by crewshin** [comment]
I have the same issue.

Logs:
`2016-09-06T20:34:18.572320+00:00 heroku[web.1]: State changed from crashed to starting
2016-09-06T20:34:20.162122+00:00 heroku[web.1]: Starting process with command `bin/slackin --coc "$SLACK_COC" --channels "$SLACK_CHANNELS" --port 27271 foo fadf-345623453455-23543455234-345234525-2687978689`
2016-09-06T20:34:22.808377+00:00 app[web.1]: module.js:341
2016-09-06T20:34:22.808396+00:00 app[web.1]:     throw err;
2016-09-06T20:34:22.808397+00:00 app[web.1]:     ^
2016-09-06T20:34:22.808398+00:00 app[web.1]:
2016-09-06T20:34:22.808403+00:00 app[web.1]: Error: Cannot find module './../dist'
2016-09-06T20:34:22.808404+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:339:15)
2016-09-06T20:34:22.808404+00:00 app[web.1]:     at Function.Module._load (module.js:290:25)
2016-09-06T20:34:22.808405+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-09-06T20:34:22.808405+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-09-06T20:34:22.808406+00:00 app[web.1]:     at Object.<anonymous> (/app/bin/slackin:5:15)
2016-09-06T20:34:22.808406+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-09-06T20:34:22.808407+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-09-06T20:34:22.808408+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-09-06T20:34:22.808409+00:00 app[web.1]:     at Function.Module.runMain (module.js:447:10)
2016-09-06T20:34:22.808408+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-09-06T20:34:22.949323+00:00 heroku[web.1]: State changed from starting to crashed
2016-09-06T20:34:22.927761+00:00 heroku[web.1]: Process exited with status 1`

Seems to be a problem with the dist folder (which I'm assuming is the output from babel), but what I'm not sure of is why it's having a hard time finding that dir.

**Comment by aryzle** [comment]
check out #229

**Comment by crewshin** [comment]
Thanks @aryzle. Good enough for now but would still like to know why it's not building that dir.

**Comment by rootical** [comment]
Still getting 
```
2016-09-20T11:23:46.364878+00:00 app[web.1]: drwx------  2 u50540 dyno 4096 Sep 20 11:22 assets
2016-09-20T11:23:46.364879+00:00 app[web.1]: -rw-------  1 u50540 dyno 1722 Sep 20 11:22 iframe.js
2016-09-20T11:23:46.364879+00:00 app[web.1]: -rw-------  1 u50540 dyno 1543 Sep 20 11:22 badge.js
2016-09-20T11:23:46.364880+00:00 app[web.1]: -rw-------  1 u50540 dyno 6983 Sep 20 11:22 index.js
2016-09-20T11:23:46.364880+00:00 app[web.1]: -rw-------  1 u50540 dyno 1544 Sep 20 11:22 log.js
2016-09-20T11:23:46.364881+00:00 app[web.1]: -rw-------  1 u50540 dyno   13 Sep 20 11:22 popup.js
2016-09-20T11:23:46.364881+00:00 app[web.1]: -rw-------  1 u50540 dyno 1929 Sep 20 11:22 slack-invite.js
2016-09-20T11:23:46.364882+00:00 app[web.1]: -rw-------  1 u50540 dyno 5119 Sep 20 11:22 slack.js
2016-09-20T11:23:46.364883+00:00 app[web.1]: -rw-------  1 u50540 dyno 8337 Sep 20 11:22 splash.js
2016-09-20T11:26:26.654106+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=frontend-pl.herokuapp.com request_id=1c709205-f219-41e0-86b7-cef452a4a24e fwd="81.210.78.142" dyno= connect= service= status=503 bytes=
2016-09-20T11:02:49.488453+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=frontend-pl.herokuapp.com request_id=d5d5b363-9b7c-4d4e-8e09-b73eb8265da6 fwd="81.210.78.142" dyno= connect= service= status=503 bytes=
```

Using latest master. `dist` structure at the heroku is like after `gulp` command.

**Comment by carloshpdoc** [comment]
I have the same issue.

**Comment by ashblue** [comment]
Having the same error

**Comment by jamesgraham** [comment]
Anyone know a workaround? Should Heroku be removed from supported deploys in the meantime?

**Comment by xuanzi23** [comment]
same for me

**Comment by KvalheimRacing** [comment]
You guys should add in the readme that the Heroku slack domain adress _only requires the team specific adress_, not the entire slack adress. So where it stands `SLACK_SUBDOMAIN`, you should only write `myteamname`. You will get an H10 error code if you write `myteamname.slack.com`.
