### ISSUE TITLE
slackin always crashes with "SyntaxError: Unexpected reserved word" at line 39 in index.js

### ISSUE THREAD

**Issue by abenbecker** [rauchg/slackin#244]
On CentOS 7, installed fresh npm and slackin with no other node packages and I consistently get this error when I try to run slackin:

```
/usr/lib/node_modules/slackin/node_modules/args/dist/index.js:39
class Args {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/slackin/bin/slackin:4:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Are there more modules I need to get this to work? It is because I've already got Apache running n this server that the error occurs?

**Comment by joelmeyerhamme** [comment]
Using node version >= 4 worked for me.
