### ISSUE TITLE
events.js:141, throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by iamjono** [rauchg/slackin#250]
Ubuntu 16.04.1
After several months of Slackin "just working", all of a sudden it's stopped, and starting it again I get the following:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1224:19)
    at listen (net.js:1273:10)
    at net.js:1382:9
    at nextTickCallbackWith3Args (node.js:452:9)
    at process._tickCallback (node.js:358:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3
```

Any ideas why? How to get it going again?

**Comment by serranoarevalo** [comment]
@iamjono How did you fix this?
