### ISSUE TITLE
TypeError: Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by rinasek** [rauchg/slackin#252]
I tried deploy on Heroku and got this:

`2016-10-24T11:23:06.880561+00:00 app[web.1]: Mon Oct 24 2016 11:23:06 GMT+0000 (UTC) – fetching
2016-10-24T11:23:06.924810+00:00 app[web.1]: Mon Oct 24 2016 11:23:06 GMT+0000 (UTC) – listening on 0.0.0.0:53668
2016-10-24T11:23:06.927880+00:00 app[web.1]: Mon Oct 24 2016 11:23:06 GMT+0000 (UTC) – Error: getaddrinfo ENOTFOUND http http:443
2016-10-24T11:23:06.927882+00:00 app[web.1]:     at errnoException (dns.js:27:10)
2016-10-24T11:23:06.927883+00:00 app[web.1]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
2016-10-24T11:23:06.928851+00:00 app[web.1]: Mon Oct 24 2016 11:23:06 GMT+0000 (UTC) – retrying
2016-10-24T11:23:06.932518+00:00 app[web.1]: /app/dist/slack.js:59
2016-10-24T11:23:06.932520+00:00 app[web.1]:         var team = res.body.team;
2016-10-24T11:23:06.932521+00:00 app[web.1]:                       ^
2016-10-24T11:23:06.932522+00:00 app[web.1]: 
2016-10-24T11:23:06.932522+00:00 app[web.1]: TypeError: Cannot read property 'body' of undefined
2016-10-24T11:23:06.932523+00:00 app[web.1]:     at /app/dist/slack.js:59:23
2016-10-24T11:23:06.932524+00:00 app[web.1]:     at Request.callback (/app/node_modules/superagent/lib/node/index.js:746:30)
2016-10-24T11:23:06.932525+00:00 app[web.1]:     at ClientRequest.<anonymous> (/app/node_modules/superagent/lib/node/index.js:711:10)
2016-10-24T11:23:06.932525+00:00 app[web.1]:     at emitOne (events.js:77:13)
2016-10-24T11:23:06.932526+00:00 app[web.1]:     at ClientRequest.emit (events.js:169:7)
2016-10-24T11:23:06.932526+00:00 app[web.1]:     at TLSSocket.socketErrorListener (_http_client.js:269:9)
2016-10-24T11:23:06.932527+00:00 app[web.1]:     at emitOne (events.js:77:13)
2016-10-24T11:23:06.932528+00:00 app[web.1]:     at TLSSocket.emit (events.js:169:7)
2016-10-24T11:23:06.932529+00:00 app[web.1]:     at connectErrorNT (net.js:1012:8)
2016-10-24T11:23:06.932532+00:00 app[web.1]:     at nextTickCallbackWith2Args (node.js:442:9)
2016-10-24T11:23:23.083967+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=drupalsrbija.herokuapp.com request_id=6383bb68-baca-496b-8fe7-3261146edca7 fwd="109.92.128.6" dyno= connect= service= status=503 bytes=
2016-10-24T11:23:24.326768+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=drupalsrbija.herokuapp.com request_id=9045888e-dd41-4d0e-9bbe-7a491552aef9 fwd="109.92.128.6" dyno= connect= service= status=503 bytes=`

**Comment by saurgoel** [comment]
Any updates on this? Facing this
`undefined:Server Error:
 { TypeError: Cannot read property 'body' of undefined
    at eval (webpack:///./src/helpers/LocationsHelper/index.js?:89:31)
    at Request.callback (/var/app/current/node_modules/superagent/lib/node/index.js:688:3)
    at ClientRequest.<anonymous> (/var/app/current/node_modules/superagent/lib/node/index.js:615:10)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function: next] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  domainThrown: true } TypeError: Cannot read property 'body' of undefined
    at eval (webpack:///./src/helpers/LocationsHelper/index.js?:89:31)
    at Request.callback (/var/app/current/node_modules/superagent/lib/node/index.js:688:3)
    at ClientRequest.<anonymous> (/var/app/current/node_modules/superagent/lib/node/index.js:615:10)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at connectErrorNT (net.js:1021:8)`

**Comment by jarradh** [comment]
Also got this on redeploy

**Comment by mz2** [comment]
Yep, getting the same too.

**Comment by serranoarevalo** [comment]
How did you fix this??

**Comment by awcchungster** [comment]
Wow, this sucks. IT's 2019, and we have gotten 0 support here. I'm running into this issue now.

**Comment by sojoudian** [comment]
did anyone fix this shit?
