### ISSUE TITLE
Heroku deploy gives application error

### ISSUE THREAD

**Issue by jamesgraham** [rauchg/slackin#264]
Fresh deploy gives

```
2017-01-22T17:15:47.806456+00:00 app[web.1]:     at emitOne (events.js:77:13)
2017-01-22T17:15:47.806457+00:00 app[web.1]:     at Request.emit (events.js:169:7)
2017-01-22T17:15:47.806458+00:00 app[web.1]:     at Stream.<anonymous> (/app/node_modules/superagent/lib/node/index.js:938:12)
2017-01-22T17:15:47.806458+00:00 app[web.1]:     at emitNone (events.js:72:20)
2017-01-22T17:15:47.806459+00:00 app[web.1]:     at Stream.emit (events.js:166:7)
2017-01-22T17:15:47.806466+00:00 app[web.1]:     at Unzip.<anonymous> (/app/node_modules/superagent/lib/node/utils.js:124:12)
2017-01-22T17:15:47.806473+00:00 app[web.1]:     at emitNone (events.js:72:20)
2017-01-22T17:15:47.892465+00:00 heroku[web.1]: Process exited with status 1
2017-01-22T17:15:47.911773+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-22T17:15:49.265598+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=salesvps.herokuapp.com request_id=b2885b6c-99df-4bdb-bae3-8a8b57522afb fwd="89.186.207.46" dyno= connect= service= status=503 bytes=
2017-01-22T17:15:50.325785+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=salesvps.herokuapp.com request_id=13d3d582-1c18-4dbf-803a-dee48caa3558 fwd="89.186.207.46" dyno= connect= service= status=503 bytes=

**Comment by gazpachu** [comment]
Same thing here :(

**Comment by gazpachu** [comment]
@leo @rauchg any idea on how to fix this?

**Comment by MikkCZ** [comment]
Same for me. I have create a Slack App and copied its secret as the API key, but despite the deploy procedure ended up gree, I see `2017-02-04T14:42:35.663798+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=xxx-slackin.herokuapp.com request_id=2101174c-ec54-4731-adc2-24357fdeb3ad fwd="xx.xx.xx.xx" dyno= connect= service= status=503 bytes=` in the log each time trying to access the site.

**Comment by MikkCZ** [comment]
False alert - works for me after I realized my account is not admin. So needed to use admin account and its test token.

**Comment by asampat3090** [comment]
Thanks for the pointers! had the same issue and resolved it with an admin token

**Comment by sadeajayi** [comment]
im having this same issue on deploying. The message im getting is 


2017-08-05T19:28:54.037736+00:00 app[web.1]: npm ERR! Failed at the watado@1.0.0 start script 'node app'.
2017-08-05T19:28:54.037916+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-08-05T19:28:54.038028+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the watado package,
2017-08-05T19:28:54.038131+00:00 app[web.1]: npm ERR! not with npm itself.
2017-08-05T19:28:54.038235+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-08-05T19:28:54.038336+00:00 app[web.1]: npm ERR!     node app
2017-08-05T19:28:54.038444+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-08-05T19:28:54.038546+00:00 app[web.1]: npm ERR!     npm bugs watado
2017-08-05T19:28:54.038654+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-08-05T19:28:54.038748+00:00 app[web.1]: npm ERR!     npm owner ls watado
2017-08-05T19:28:54.038856+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-08-05T19:28:54.039022+00:00 app[web.1]: npm verb exit [ 1, true ]
2017-08-05T19:28:54.043584+00:00 app[web.1]: 
2017-08-05T19:28:54.043766+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-08-05T19:28:54.043852+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-08-05T19:28:54.142005+00:00 heroku[web.1]: State changed from starting to crashed
2017-08-05T19:28:54.128787+00:00 heroku[web.1]: Process exited with status 1
2017-08-05T19:29:21.797489+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=immense-oasis-48022.herokuapp.com request_id=693b1444-7f4a-4617-9bcb-4c458c9f1247 fwd="173.69.172.120" dyno= connect= service= status=503 bytes= protocol=https
2017-08-05T19:29:22.096275+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=immense-oasis-48022.herokuapp.com request_id=ad89c025-cc0c-4f68-a3a8-92e42d4fb1d2 fwd="173.69.172.120" dyno= connect= service= status=503 bytes= protocol=https`
