### ISSUE TITLE
Running on my server

### ISSUE THREAD

**Issue by eva-thien** [rauchg/slackin#31]
Hi

I try install it on Heroku but it not woking, because I use free Heroku, then I try running on my server but not woking

Here error:

```
Wed Apr 01 2015 14:04:12 GMT+0700 (ICT) – retrying
Wed Apr 01 2015 14:04:14 GMT+0700 (ICT) – fetching
Wed Apr 01 2015 14:04:15 GMT+0700 (ICT) – Error: Hostname/IP doesn't match certificate's altnames
    at SecurePair.<anonymous> (tls.js:1390:23)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:980:10)
    at CleartextStream.read [as _read] (tls.js:472:13)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)
Wed Apr 01 2015 14:04:15 GMT+0700 (ICT) – retrying
Wed Apr 01 2015 14:04:17 GMT+0700 (ICT) – fetching
Wed Apr 01 2015 14:04:18 GMT+0700 (ICT) – Error: Hostname/IP doesn't match certificate's altnames

```

Anyone help  me suggestion a  solutions?

**Comment by skurfuerst** [comment]
Hey,

I have the same issue but do not know yet what's going on there...

Some pointer would be awesome :dancer: 

Greets, Sebastian

**Comment by maccman** [comment]
Also getting this.

**Comment by maccman** [comment]
Set the env var `NODE_TLS_REJECT_UNAUTHORIZED` to `0`

**Comment by eva-thien** [comment]
Hi 

I have been running again via command

```
 slackin --port 8080 --interval 60000 "phalconchats"  "tokenslack"
```

And working

**Comment by sigwo** [comment]
@maccman Where is that set in slackin?

**Comment by bryanjacquot** [comment]
I was getting this same error and I fixed it by setting the "your-slack-subdomain". In our case, this was the first portion of **grommet**.slack.com (grommet).

**Comment by zavg** [comment]
Thank you, @maccman 

Your suggestion to

> Set the env var NODE_TLS_REJECT_UNAUTHORIZED to 0

worked for me!

**Comment by jontsai** [comment]
Thanks @maccman , I fixed this on Heroku by doing

`heroku config:set NODE_TLS_REJECT_UNAUTHORIZED=0 --app APP_NAME`

**Comment by rauchg** [comment]
@jontsai why do we need this TLS warn in the first place? I wasn't getting this error myself.

**Comment by kalashnikovisme** [comment]
@sigwo setting env variables is looking like this.

```shell
NODE_TLS_REJECT_UNAUTHORIZED=0 slackin "yourdomain" "yourtoken"
```
