### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by gustavopalencia** [rauchg/slackin#331]
https://aidax-slack.herokuapp.com/
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

2017-08-04T03:04:50.202244+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-08-04T03:04:50.202244+00:00 app[web.1]:     at Request.emit (events.js:188:7)
2017-08-04T03:04:50.202245+00:00 app[web.1]:     at Stream.<anonymous> (/app/node_modules/superagent/lib/node/index.js:938:12)
2017-08-04T03:04:50.202245+00:00 app[web.1]:     at emitNone (events.js:91:20)
2017-08-04T03:04:50.202245+00:00 app[web.1]:     at Stream.emit (events.js:185:7)
2017-08-04T03:04:50.202246+00:00 app[web.1]:     at Unzip.<anonymous> (/app/node_modules/superagent/lib/node/utils.js:124:12)
2017-08-04T03:04:50.202246+00:00 app[web.1]:     at emitNone (events.js:91:20)
2017-08-04T03:04:50.275548+00:00 heroku[web.1]: State changed from starting to crashed
2017-08-04T03:04:50.262929+00:00 heroku[web.1]: Process exited with status 1
2017-08-04T03:05:13.189688+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=aidax-slack.herokuapp.com request_id=84cb5fa7-995f-4eb8-949c-e8fcc814ed55 fwd="177.189.202.159" dyno= connect= service= status=503 bytes= protocol=https
2017-08-04T03:05:16.656824+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=aidax-slack.herokuapp.com request_id=21ff138a-c3ca-47cf-9fa1-b83b8710accb fwd="177.189.202.159" dyno= connect= service= status=503 bytes= protocol=https
 Autoscroll with output

**Comment by turkishdeveloper** [comment]
If you don't want to bother installing or have a website. Feel free to use Community Inviter :) https://communityinviter.com

**Comment by kontractorz** [comment]
> If you don't want to bother installing or have a website. Feel free to use Community Inviter :) https://communityinviter.com

Great tool! Thanks for sharing @humma-kavula
