### ISSUE TITLE
Slackin heroic deployment broken?

### ISSUE THREAD

**Issue by Zuse2k** [rauchg/slackin#338]
Hi,
if I wanna deploy slackin at heroku I get following error messages.

`-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  6.11.1
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 6.11.1...
       Downloading and installing node 6.11.1...
       Using default npm version: 3.10.10
-----> Restoring cache
       Skipping cache restore (not-found)
-----> Building dependencies
       Installing node modules (package.json)
       
       > slackin@0.14.0 postinstall /tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d
       > gulp
       
       [17:32:13] Requiring external module babel-core/register
       [17:32:13] Using gulpfile /tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d/gulpfile.babel.js
       [17:32:13] Starting 'transpile'...
       [17:32:13] Starting 'assets'...
       
       events.js:160
       throw er; // Unhandled 'error' event
       ^
       Error: Plugin 19 specified in "/tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d/node_modules/babel-preset-es2015/index.js" provided an invalid property of "name"
       at Plugin.init (/tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d/node_modules/babel-core/lib/transformation/plugin.js:127:13)
       at Function.normalisePlugin (/tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d/node_modules/babel-core/lib/transformation/file/options/option-manager.js:167:12)
       at /tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d/node_modules/babel-core/lib/transformation/file/options/option-manager.js:197:30
       at Array.map (native)
       at Function.normalisePlugins (/tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
       at OptionManager.mergeOptions (/tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
       at OptionManager.mergePresets (/tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d/node_modules/babel-core/lib/transformation/file/options/option-manager.js:325:16)
       at OptionManager.mergeOptions (/tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d/node_modules/babel-core/lib/transformation/file/options/option-manager.js:287:12)
       at OptionManager.addConfig (/tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
       at OptionManager.findConfigs (/tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:30)
       
       npm ERR! Linux 3.13.0-128-generic
       npm ERR! argv "/tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d/.heroku/node/bin/node" "/tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d/.npmrc"
       npm ERR! node v6.11.1
       npm ERR! npm  v3.10.10
       npm ERR! code ELIFECYCLE
       npm ERR! slackin@0.14.0 postinstall: `gulp`
       npm ERR! Exit status 1
       npm ERR!
       npm ERR! Failed at the slackin@0.14.0 postinstall script 'gulp'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the slackin package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     gulp
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs slackin
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls slackin
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_d50a0995bdb4ba8f20bedc55c938322f/rauchg-slackin-f3e3b3d/npm-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed`

**Comment by scrubbs** [comment]
Just deployed current version to Heroku today with no errors  at cincypy.herokuapp.com

**Comment by HansHovanitz** [comment]
@scrubbs I tried to deploy on Heroku. I forked this repo's master and then did a a manual github deployment from that branch. It seemed in deploy fine but when I went to look at the page it just says 'Application Error'. 
How did you do your deployment? And where did you enter the subdomain/apitoken/captcha stuff? When deploying via NOW is will ask for it but I'm not sure how to put it in doing a Heroku deployment.

**Comment by turkishdeveloper** [comment]
you can use community inviter :) Thats much more easy :) http://communityinviter.com

**Comment by scrubbs** [comment]
I deployed with the link on the readme with no issues. Did not do by hand. https://heroku.com/deploy?template=https://github.com/rauchg/slackin/tree/master

**Comment by Zuse2k** [comment]
It is also ok for me now. But does the invite work at your instance ? If I enter a email and click on invite I get "Please wait" and nothing happens - no invite email. Like : https://github.com/rauchg/slackin/issues/165

**Comment by scrubbs** [comment]
My deploy works fine. I don't think the issue is with Slackin.
