### ISSUE TITLE
Deployed to heroku ok but application crashes on launch

### ISSUE THREAD

**Issue by steveharman** [rauchg/slackin#409]
Everything edployed to heorku without error, but when I try to open the app from within the heroku web interface I'm told there is an Application Error.

Examining the app's log from the heroku cli reveals:
```
2019-10-24T14:55:41.843711+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=slackinkeyshape.herokuapp.com request_id=a44dbec5-5223-4edf-985f-4331feaa76b2 fwd="81.131.144.153" dyno= connect= service= status=503 bytes= protocol=https
2019-10-24T14:55:42.147759+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=slackinkeyshape.herokuapp.com request_id=c93a45bd-ce4d-4d4f-a6e2-98c68d298049 fwd="81.131.144.153" dyno= connect= service= status=503 bytes= protocol=https

```
Does anyone have any ideas?

Thanks

**Comment by XhmikosR** [comment]
You should try https://github.com/emedvedev/slackin-extended. Do note that there's a bug with many users in both repos.

**Comment by steveharman** [comment]
Thanks, I didn't know about that.  I gave it a try but am getting a build failure from `now ./slackin-extended`.

```
04:06:44 PM | WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
04:06:44 PM | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
04:06:44 PM | added 736 packages from 900 contributors and audited 4673 packages in 9.507s
04:06:44 PM | found 0 vulnerabilities
04:06:44 PM | Running "npm run build"
04:06:44 PM | > slackin-extended@1.1.11 build /zeit/219c027a
04:06:44 PM | > node-sass --output-style compressed --precision 6 scss/ -o assets/
04:06:45 PM | Rendering Complete, saving .css file...
04:06:45 PM | Wrote CSS to /zeit/219c027a/assets/main.css
04:06:45 PM | Wrote 1 CSS files to /zeit/219c027a/assets/
04:06:45 PM | Error: No output directory named "public" found.
04:06:45 PM | More details: https://zeit.co/docs/v2/advanced/platform/frequently-asked-questions#missing-public-directory
04:06:45 PM | at validateDistDir (/zeit/55cfbb27218c985e/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:308:15)
04:06:45 PM | at Object.build (/zeit/55cfbb27218c985e/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:503:13)
04:06:45 PM | at <anonymous>
04:06:45 PM | at process._tickDomainCallback (internal/process/next_tick.js:228:7)
04:06:45 PM | worker exited with code 20 and signal null
04:06:47 PM | done
```

**Comment by XhmikosR** [comment]
You should ask in the other repo :) I don't use Zeit myself

**Comment by Aman-Aalam** [comment]
I deployed successfully after a few tries.
Check if your reCaptcha keys are right
