### ISSUE TITLE
Unhandle exception

### ISSUE THREAD

**Issue by vluzrmos** [rauchg/slackin#49]
My server down after hours online ... with the following exception:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Invalid Slack response: 504
    at SlackData.onres (/var/www/slackin.vluzrmos.com.br/node_modules/slackin/node/slack.js:87:22)
    at /var/www/slackin.vluzrmos.com.br/node_modules/slackin/node/slack.js:42:17
    at Request.callback (/var/www/slackin.vluzrmos.com.br/node_modules/slackin/node_modules/superagent/lib/node/index.js:746:30)
    at Request.<anonymous> (/var/www/slackin.vluzrmos.com.br/node_modules/slackin/node_modules/superagent/lib/node/index.js:135:10)
    at Request.EventEmitter.emit (events.js:95:17)
    at ClientRequest.<anonymous> (/var/www/slackin.vluzrmos.com.br/node_modules/slackin/node_modules/superagent/lib/node/index.js:921:12)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
```

**Comment by chrisfranko** [comment]
I get this too, how to keep it runing?

**Comment by vluzrmos** [comment]
IDK,
I just create my own invitator. :/

**Comment by alexgleason** [comment]
Also getting a similar error. The server crashes after several days of being up.

```
2016-06-05T18:32:38.814132598Z app[web.1]: events.js:154
2016-06-05T18:32:38.814295774Z app[web.1]:       throw er; // Unhandled 'error' event
2016-06-05T18:32:38.814318448Z app[web.1]:       ^
2016-06-05T18:32:38.814349913Z app[web.1]: 
2016-06-05T18:32:38.814376909Z app[web.1]: Error: unexpected end of file
2016-06-05T18:32:38.814385204Z app[web.1]:     at Zlib._handle.onerror (zlib.js:370:17)
```

**Comment by Chandler** [comment]
Got this error after 8 hours of being up, not using slackin, using https://github.com/ttezel/twit

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)

**Comment by alexgleason** [comment]
We've "resolved" this by using [forever](https://github.com/foreverjs/forever) to load slackin.

See my repo here. https://github.com/directactioneverywhere/dxe-slack-inviter
