### ISSUE TITLE
v0.5.0 crashes if can't get the channel list from Slack

### ISSUE THREAD

**Issue by viktorbenei** [rauchg/slackin#58]
Started yesterday when Slack reported connectivity issues, we experienced one more crash after that. IMO Slackin should handle this case (when it can't get the channel list or other non crucial information from Slack API) instead of crashing.

Here are the logs:

    Tue May 12 2015 14:42:54 GMT+0000 (UTC) – online 1, total 5 (+481ms)
    Tue May 12 2015 14:42:55 GMT+0000 (UTC) – fetching
    Tue May 12 2015 14:42:55 GMT+0000 (UTC) – online 1, total 5 (+426ms)
    Tue May 12 2015 14:42:56 GMT+0000 (UTC) – fetching

    /usr/local/lib/node_modules/slackin/node/slack.js:70
            res.body.channels.forEach(function (channel) {
                              ^
    TypeError: Cannot call method 'forEach' of undefined
        at SlackData.onres (/usr/local/lib/node_modules/slackin/node/slack.js:70:27)
        at /usr/local/lib/node_modules/slackin/node/slack.js:41:17
        at Request.callback (/usr/local/lib/node_modules/slackin/node_modules/superagent/lib/node/index.js:746:30)
        at Request.<anonymous> (/usr/local/lib/node_modules/slackin/node_modules/superagent/lib/node/index.js:135:10)
        at Request.emit (events.js:95:17)
        at ClientRequest.<anonymous> (/usr/local/lib/node_modules/slackin/node_modules/superagent/lib/node/index.js:921:12)
        at ClientRequest.emit (events.js:95:17)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1689:21)
        at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
        at CleartextStream.socketOnData [as ondata] (http.js:1584:20)

**Comment by vluzrmos** [comment]
Maybe your token is not admin or your internet connection is troubling... to download the list of channels, in my case it download more than 3MB.

**Comment by viktorbenei** [comment]
Definitely an API connection issue but (it seems) it wasn't our fault but the recent issue on Slack's side as you can see it on their status page https://status.slack.com/

IMO this (if Slack API is down) should be handled properly (presenting an error message for example) and should not crash the slackin server.

**Comment by NextGenDan** [comment]
Same issue. Slackin has actually been crashing on a daily basis with this error for me.

**Comment by viktorbenei** [comment]
For others facing this issue and looking for a solution: temporarily we fixed this by using Docker to run Slackin and we set a restart policy "always" for the container. Not an ideal fix but seems to be working.

**Comment by underscorephil** [comment]
Having the same issue here as well. Crashes multiple times a day.

**Comment by underscorephil** [comment]
Added this conditional and haven't had a crash in a few days. Not sure if its the best route, or if there will be any side effects. No issues apparent.

https://github.com/underscorephil/houstontech-site/blob/master/lib/slack.js#L45

**Comment by maccman** [comment]
We're seeing this too :(

**Comment by jeanleonino** [comment]
Just started getting this problem. Will try reinstalling everything. Any advance on this?

**Comment by jeanleonino** [comment]
The problem appears to be on this: https://github.com/rauchg/slackin/blob/master/lib/slack.js#L24 

A similar solution to what @underscorephil suggested may be the answer. But I can't fix it now. =/
