### ISSUE TITLE
Deploying to Heroku not working

### ISSUE THREAD

**Issue by ilukac** [rauchg/slackin#65]
I get only this message:

There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.

**Comment by ilukac** [comment]
Noticed one more message:

Unable to fetch source from: https://api.github.com/repos/rauchg/slackin/tarball/0.5.0

**Comment by ilukac** [comment]
Seems that it was some temp issue, it was successful on 3rd try

**Comment by jbnv** [comment]
I got a lot of error barf when I tried to deploy it to Heroku using their command. I have included it below. This is my first deployment to Heroku. I'll try deploying it directly from my machine.

> C:\\Users\\Jay\\Documents\\Git\\lcusa-slack>heroku git:remote -a lcusa-slack
> Setting up iojs-v3.2.0... done
> Installing core plugins heroku-apps, heroku-fork, heroku-git, heroku-local, heroku-run, heroku-status...
>      module.js:338
>          throw err;
>          ^
>      Error: Cannot find module 'C:\\Users\\Jay\\.heroku\\iojs-v3.2.0-windows-x86\\lib\\node_modules\\npm\\cli.js'
>          at Function.Module._resolveFilename (module.js:336:15)
>          at Function.Module._load (module.js:286:25)
>          at Function.Module.runMain (module.js:471:10)
>          at startup (node.js:117:18)
>          at node.js:951:3
> Setting up iojs-v3.2.0... done
> Installing core plugins heroku-apps, heroku-fork, heroku-git, heroku-local, heroku-run, heroku-status...
>      module.js:338
>          throw err;
>          ^
>      Error: Cannot find module 'C:\\Users\\Jay\\.heroku\\iojs-v3.2.0-windows-x86\\lib\\node_modules\\npm\\cli.js'
>          at Function.Module._resolveFilename (module.js:336:15)
>          at Function.Module._load (module.js:286:25)
>          at Function.Module.runMain (module.js:471:10)
>          at startup (node.js:117:18)
>          at node.js:951:3
> ERROR: module.js:338
>     throw err;
>     ^
> Error: Cannot find module 'C:\\Users\\Jay\\.heroku\\iojs-v3.2.0-windows-x86\\lib\\node_modules\\npm\\cli.js'
>     at Function.Module._resolveFilename (module.js:336:15)
>     at Function.Module._load (module.js:286:25)
>     at Function.Module.runMain (module.js:471:10)
>     at startup (node.js:117:18)
>     at node.js:951:3
> 
> Setting up iojs-v3.2.0... done
> Installing core plugins heroku-apps, heroku-fork, heroku-git, heroku-local, heroku-run, heroku-status... done
> Installing plugin heroku-git... done
>      128: Command failed: git remote
>      fatal: Not a git repository (or any of the parent directories): .git
